### ISSUE TITLE
CoppeliaSensor无法导入

### ISSUE THREAD

**Issue by BrightMoonStar** [beatriz-emiliano/yolov3_ros_coppeliasim#1]
请问from include.coppeliasim import CoppeliaSim, CoppeliaArmRobot,CoppeliaSensor这行代码中的相关包如何导入呢？

**Comment by beatriz-emiliano** [comment]
HI, BrighttMoonStar. Sorry, I forgot to add the coppeliasim.py file, now it's working normally.
